-- Restaurant partner subscription. Restaurants pay an annual fee (settings.subscription_fee_cents,
-- plus HST at settings.default_tax_rate_bps) by card in the Partner Portal. Each paid year starts when
-- the current one ends, so renewing early never loses time. While settings.require_subscription is on,
-- a restaurant needs an active subscription to post or resume offers; offers already live keep running
-- until their discard timers end. Admins can also grant a complimentary year.

insert into public.settings (key, value) values
  ('subscription_fee_cents', '10000'),
  ('require_subscription', 'true')
on conflict (key) do nothing;

-- The Restaurant Partner Agreement now covers the subscription (section 5.3), so restaurants re-accept it.
update public.legal_documents set version = '2026-10-04.1' where id = 'restaurant-agreement';

create type public.subscription_payment_status as enum ('pending', 'paid', 'failed');
create type public.subscription_payment_kind as enum ('card', 'complimentary');

-- One row per payment attempt (or complimentary year). Paid rows carry the period they cover and a
-- system-assigned invoice number (SUB-YYYYMMDD-000001, Newfoundland date).
create table public.subscription_payments (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  kind public.subscription_payment_kind not null default 'card',
  status public.subscription_payment_status not null default 'pending',
  fee_cents integer not null check (fee_cents >= 0),
  tax_rate_bps integer not null check (tax_rate_bps between 0 and 2000),
  tax_cents integer not null check (tax_cents >= 0),
  total_cents integer not null,
  period_start timestamptz,
  period_end timestamptz,
  payment_ref text,
  card_label text not null default '',
  invoice_number text unique,
  note text not null default '',
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  check (total_cents = fee_cents + tax_cents),
  check (status <> 'paid' or (period_end > period_start and invoice_number is not null and paid_at is not null))
);
create index subscription_payments_restaurant_idx on public.subscription_payments (restaurant_id, created_at desc);

alter table public.subscription_payments enable row level security;
revoke insert, update, delete, truncate on public.subscription_payments from anon, authenticated;
create policy "owners and admins read subscription payments" on public.subscription_payments for select to authenticated
  using (restaurant_id = (select public.my_restaurant_id()) or (select public.is_admin()));

-- ---------------------------------------------------------------- status

-- End of the last paid year (null = never subscribed).
create function public.subscription_paid_through(p_restaurant_id bigint) returns timestamptz
language sql stable security definer set search_path = public as $$
  select max(period_end) from public.subscription_payments where restaurant_id = p_restaurant_id and status = 'paid';
$$;

create function public.subscription_active(p_restaurant_id bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select not public.setting_bool('require_subscription')
    or coalesce(public.subscription_paid_through(p_restaurant_id) > now(), false);
$$;

-- What a year costs now: the fee plus HST.
create function public._subscription_price() returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  fee integer := coalesce(public.setting_int('subscription_fee_cents'), 10000);
  rate integer := coalesce(public.setting_int('default_tax_rate_bps'), 1500);
  tax integer := floor((fee * rate)::numeric / 10000 + 0.5);
begin
  return jsonb_build_object('feeCents', fee, 'taxRateBps', rate, 'taxCents', tax, 'totalCents', fee + tax);
end;
$$;

-- Renewals open 60 days before the paid year ends.
create function public._subscription_renewable(p_paid_through timestamptz) returns boolean
language sql immutable as $$
  select p_paid_through is null or p_paid_through <= now() + interval '60 days';
$$;

-- The signed-in restaurant's subscription, for the Partner Portal.
create function public.my_subscription() returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  rid bigint := public.my_restaurant_id();
  through timestamptz;
begin
  if rid is null then
    raise exception 'Restaurant profile not found.' using errcode = 'BB404';
  end if;
  through := public.subscription_paid_through(rid);
  return public._subscription_price() || jsonb_build_object(
    'paidThrough', through,
    'active', coalesce(through > now(), false),
    'endsSoon', coalesce(through > now() and through <= now() + interval '30 days', false),
    'required', public.setting_bool('require_subscription'),
    'canRenew', public._subscription_renewable(through)
  );
end;
$$;

-- ---------------------------------------------------------------- payments (server only)

-- Starts a card payment for one year. Payments abandoned for 30 minutes (e.g. 3-D Secure never
-- finished) are marked failed; a newer one still in progress blocks a second charge.
create function public.begin_subscription_payment(p_restaurant_id bigint) returns public.subscription_payments
language plpgsql security definer set search_path = public as $$
declare
  r public.restaurants;
  through timestamptz;
  price jsonb := public._subscription_price();
  v public.subscription_payments;
begin
  select * into r from public.restaurants where id = p_restaurant_id for update;
  if r.id is null then
    raise exception 'Restaurant not found.' using errcode = 'BB404';
  end if;
  if r.status = 'suspended' then
    raise exception 'Your restaurant is suspended. Please contact Last Bite support.' using errcode = 'BB403';
  end if;
  through := public.subscription_paid_through(r.id);
  if not public._subscription_renewable(through) then
    raise exception 'Your subscription is paid until %. You can renew from 60 days before that date.',
      to_char(through at time zone 'America/St_Johns', 'FMMonth FMDD, YYYY') using errcode = 'BB409';
  end if;
  update public.subscription_payments set status = 'failed'
  where restaurant_id = r.id and status = 'pending' and created_at < now() - interval '30 minutes';
  if exists (select 1 from public.subscription_payments where restaurant_id = r.id and status = 'pending') then
    raise exception 'A subscription payment is already in progress. Finish it, or try again in 30 minutes.' using errcode = 'BB409';
  end if;
  insert into public.subscription_payments (restaurant_id, kind, fee_cents, tax_rate_bps, tax_cents, total_cents)
  values (r.id, 'card', (price->>'feeCents')::integer, (price->>'taxRateBps')::integer, (price->>'taxCents')::integer, (price->>'totalCents')::integer)
  returning * into v;
  return v;
end;
$$;

-- Records a successful payment: the new year starts when the current one ends (or now, if it has
-- lapsed). Safe to call twice. A payment marked failed while 3-D Secure was still open is accepted
-- too, because the card was charged.
create function public.finish_subscription_payment(p_id bigint, p_payment_ref text, p_card_label text) returns public.subscription_payments
language plpgsql security definer set search_path = public as $$
declare
  v public.subscription_payments;
  v_start timestamptz;
begin
  select * into v from public.subscription_payments where id = p_id for update;
  if v.id is null then
    raise exception 'Subscription payment not found.' using errcode = 'BB404';
  end if;
  if v.status = 'paid' then
    return v;
  end if;
  perform 1 from public.restaurants where id = v.restaurant_id for update;
  v_start := greatest(now(), coalesce(public.subscription_paid_through(v.restaurant_id), now()));
  update public.subscription_payments set
    status = 'paid', paid_at = now(), period_start = v_start, period_end = v_start + interval '1 year',
    payment_ref = coalesce(p_payment_ref, payment_ref), card_label = coalesce(p_card_label, card_label),
    invoice_number = 'SUB-' || to_char(now() at time zone 'America/St_Johns', 'YYYYMMDD') || '-' || lpad(id::text, 6, '0')
  where id = v.id
  returning * into v;
  return v;
end;
$$;

-- A complimentary year from an admin (no charge), recorded like a payment.
create function public.grant_subscription_year(p_restaurant_id bigint, p_note text, p_by uuid) returns public.subscription_payments
language plpgsql security definer set search_path = public as $$
declare
  v public.subscription_payments;
begin
  if not exists (select 1 from public.restaurants where id = p_restaurant_id) then
    raise exception 'Restaurant not found.' using errcode = 'BB404';
  end if;
  insert into public.subscription_payments (restaurant_id, kind, fee_cents, tax_rate_bps, tax_cents, total_cents, note, created_by)
  values (p_restaurant_id, 'complimentary', 0, 0, 0, 0, coalesce(p_note, ''), p_by)
  returning * into v;
  return public.finish_subscription_payment(v.id, null, null);
end;
$$;

-- ---------------------------------------------------------------- offers need an active subscription

-- As in 20260930000100_last_bite_name.sql, plus the subscription check for new and resumed offers.
-- Creates (p_offer_id null) or edits an offer from one of the restaurant's menu items.
-- p_expires_in_minutes starts the discard timer now (5 min to 3 days); null keeps the current timer.
create or replace function public.restaurant_save_offer(
  p_offer_id bigint, p_menu_item_id bigint, p_reason public.offer_reason, p_description text,
  p_discount_pct integer, p_quantity integer, p_expires_in_minutes integer
) returns public.offers
language plpgsql security definer set search_path = public as $$
declare
  rid bigint := public.my_restaurant_id();
  r_status public.restaurant_status;
  item public.menu_items;
  existing public.offers;
  v public.offers;
  v_start timestamptz;
  v_end timestamptz;
  committed integer := 0;
  v_description text;
begin
  if rid is null then
    raise exception 'Restaurant profile not found.' using errcode = 'BB404';
  end if;
  select status into r_status from public.restaurants where id = rid;
  if p_offer_id is not null then
    select * into existing from public.offers where id = p_offer_id and restaurant_id = rid for update;
    if existing.id is null then
      raise exception 'Offer not found.' using errcode = 'BB404';
    end if;
    if existing.status = 'ended' then
      raise exception 'Ended offers cannot be edited.' using errcode = 'BB409';
    end if;
    committed := existing.quantity_total - existing.quantity_available;
  elsif r_status = 'suspended' then
    raise exception 'Your restaurant is suspended, so you cannot post offers. Please contact Last Bite support.' using errcode = 'BB403';
  elsif not public.subscription_active(rid) then
    raise exception 'Your Last Bite subscription is not active. Renew it in the Subscription tab to post offers.' using errcode = 'BB402';
  end if;

  select * into item from public.menu_items where id = p_menu_item_id and restaurant_id = rid and active;
  if item.id is null then
    raise exception 'Menu item not found.' using errcode = 'BB404';
  end if;
  if p_reason is null then
    raise exception 'Please choose why this food is available.' using errcode = 'BB400';
  end if;
  if p_discount_pct is null or p_discount_pct < 1 or p_discount_pct > 90 then
    raise exception 'Discount must be a whole number from 1 to 90.' using errcode = 'BB400';
  end if;
  if p_quantity is null or p_quantity < 1 or p_quantity > 500 then
    raise exception 'Quantity must be a whole number from 1 to 500.' using errcode = 'BB400';
  end if;
  if p_quantity < committed then
    raise exception '% already ordered, so quantity cannot be lower than that.', committed using errcode = 'BB400';
  end if;
  if char_length(coalesce(p_description, '')) > 500 then
    raise exception 'Description must be at most 500 characters.' using errcode = 'BB400';
  end if;

  if p_expires_in_minutes is not null then
    if p_expires_in_minutes < 5 or p_expires_in_minutes > 4320 then
      raise exception 'Discard timer (minutes) must be a whole number from 5 to 4320.' using errcode = 'BB400';
    end if;
    v_start := case when existing.id is not null and existing.pickup_start < now() then existing.pickup_start else now() end;
    v_end := now() + make_interval(mins => p_expires_in_minutes);
  elsif existing.id is not null then
    v_start := existing.pickup_start;
    v_end := existing.pickup_end;
  else
    raise exception 'Please set the discard timer.' using errcode = 'BB400';
  end if;

  v_description := coalesce(nullif(btrim(p_description), ''), item.description);

  if existing.id is null then
    insert into public.offers (restaurant_id, menu_item_id, image_url, title, description, reason, dietary,
      original_price_cents, discount_pct, quantity_total, quantity_available, pickup_start, pickup_end)
    values (rid, item.id, item.image_url, item.name, v_description, p_reason, item.dietary,
      item.price_cents, p_discount_pct, p_quantity, p_quantity, v_start, v_end)
    returning * into v;
  else
    -- Price changes only affect new orders; existing orders keep the price they were quoted.
    update public.offers set menu_item_id = item.id, image_url = item.image_url, title = item.name,
      description = v_description, reason = p_reason, dietary = item.dietary, original_price_cents = item.price_cents,
      discount_pct = p_discount_pct, quantity_total = p_quantity, quantity_available = p_quantity - committed,
      pickup_start = v_start, pickup_end = v_end
    where id = existing.id
    returning * into v;
    update public.orders set pickup_end = v_end where offer_id = v.id and status in ('pending_payment', 'reserved');
  end if;
  return v;
end;
$$;


create or replace function public.restaurant_set_offer_status(p_offer_id bigint, p_status public.offer_status) returns public.offers
language plpgsql security definer set search_path = public as $$
declare
  v public.offers;
  r_status public.restaurant_status;
begin
  select * into v from public.offers where id = p_offer_id and restaurant_id = public.my_restaurant_id() for update;
  if v.id is null then
    raise exception 'Offer not found.' using errcode = 'BB404';
  end if;
  if v.status = 'ended' then
    raise exception 'This offer has already ended.' using errcode = 'BB409';
  end if;
  if p_status = 'active' then
    if v.pickup_end <= now() then
      raise exception 'The pickup window has passed. Create a new offer.' using errcode = 'BB400';
    end if;
    select status into r_status from public.restaurants where id = v.restaurant_id;
    if r_status = 'suspended' then
      raise exception 'Your restaurant is suspended, so you cannot post offers. Please contact Last Bite support.' using errcode = 'BB403';
    end if;
    if not public.subscription_active(v.restaurant_id) then
      raise exception 'Your Last Bite subscription is not active. Renew it in the Subscription tab to post offers.' using errcode = 'BB402';
    end if;
  end if;
  update public.offers set status = p_status where id = v.id returning * into v;
  return v;
end;
$$;

-- ---------------------------------------------------------------- access

do $$
declare
  fn text;
begin
  foreach fn in array array[
    'public.subscription_paid_through(bigint)',
    'public.subscription_active(bigint)',
    'public._subscription_price()',
    'public._subscription_renewable(timestamptz)',
    'public.begin_subscription_payment(bigint)',
    'public.finish_subscription_payment(bigint, text, text)',
    'public.grant_subscription_year(bigint, text, uuid)'
  ] loop
    execute format('revoke execute on function %s from public, anon, authenticated', fn);
    execute format('grant execute on function %s to service_role', fn);
  end loop;
end;
$$;
revoke execute on function public.my_subscription() from public, anon;
